version: '3.7'

services:

  frontend:
    container_name: frames_frontend
    build:
      context: frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    links:
      - redis
    environment:
      - NODE_ENV=development

  redis:
    image: redis
    container_name: frames_redis
    ports:
      - '6379:6379'

volumes:
  frontend:
